pod 'SDWebImage'					# SD图片库
pod 'SVProgressHUD'					# 提示信息库
pod 'IQKeyboardManager'				# 文本输入
pod 'RDVTabBarController'              		# tabBar
pod 'MJRefresh'						# MJ刷新
pod 'MJExtension'					# MJ解析数据解析
pod 'PureLayout'					# 自动布局
pod 'UITableView+FDTemplateLayoutCell'   		# cell自适应高度
pod 'AFNetworking'					# AFNetworking 网络库
pod 'Base64nl'                            		# Base64加密
pod 'FDFullscreenPopGesture'            		# Navigation
pod 'WebViewJavascriptBridge'				# webView 交互
pod 'HTHorizontalSelectionList'			# 分类
pod 'Masonry'						# Masonry 自动布局框架
